---
title: "08_analysis_4"
format: html
editor: visual
---

```{r}
#| message: false
library("tidyverse")
library("dplyr")
library("here")
library("broom")
library("cowplot")
```

```{r}
#| message: false
data_metrics <- read_tsv(here("data","data_metrics_aug.tsv"))
data_gene <- read_tsv(here("data","data_gene_aug.tsv"))
data_score <- read_tsv(here("data","data_score_aug.tsv"))
data_code <- read_tsv(here("data","data_code_aug.tsv"))
data_diag <- read_tsv(here("data","data_diag_aug.tsv"))
```

## PCA

```{r}
data_all <- data_metrics |>
  left_join(data_gene,  by = "Patient ID") |>
  left_join(data_score, by = "Patient ID") |>
  left_join(data_code,  by = "Patient ID") |>
  left_join(data_diag,  by = "Patient ID")
```

```{r}
data_all_num <- data_all |>
  select(where(is.numeric)) |>
  select(-c(`Disease Free (days)`, 
            `Disease Free (Months)`, 
            `Disease-specific Survival status (bin)`, 
            `Progression Free Status (bin)`, 
            `Disease Free Status (bin)`)) |> 
  filter(`Mutation Count` < 5000 | is.na(`Mutation Count`)) |> 
  filter(`Tumor Break Load` < 200 | is.na(`Tumor Break Load`)) |> 
  drop_na()
```

```{r}
data_pca <- data_all_num |>
  mutate(across(
    .cols = -`Overall Survival Status (bin)`,
    .fns  = ~ if_else(is.na(.x),
                      mean(.x, na.rm = TRUE),
                      .x)
  ))
```

```{r}
pca_fit <- data_pca |> 
  select(-`Overall Survival Status (bin)`) |> 
  scale() |> 
  prcomp()
```

```{r}
pca_fit |> 
  augment(data_pca) |>  # add original dataset back in
  ggplot(aes(x = .fittedPC1, 
             y = .fittedPC2, 
             color = factor(`Overall Survival Status (bin)`))) + 
  geom_point(size = 1.5) +
  theme_half_open(12) + background_grid()
```

```{r}
pca_fit |> 
  tidy(matrix = "eigenvalues")
```

```{r}
pca_fit |> 
  tidy(matrix = "eigenvalues") |> 
  ggplot(aes(PC, cumulative)) +
  geom_col(fill = "#56B4E9", alpha = 0.8) +
  geom_hline(yintercept = 0.9,
             linetype = "dashed",
             color = "grey30",
             linewidth = 0.6) +
  scale_x_continuous(breaks = 1:17) +
  scale_y_continuous(
  breaks = c(0, 0.25, 0.5, 0.75, 0.9, 1),
  labels = scales::percent_format(),
  expand = expansion(mult = c(0, 0.01))
) +
  theme_minimal_hgrid(12) +
  labs( x = "PC",
        y = "Cumulative Variance across PC´s")
```

```{r}
arrow_style <- arrow(
  angle = 20, ends = "first", type = "closed", length = grid::unit(8, "pt")
)

# plot rotation matrix
pca_fit %>%
  tidy(matrix = "rotation") %>%
  pivot_wider(names_from = "PC", names_prefix = "PC", values_from = "value") %>%
  ggplot(aes(PC1, PC2)) +
  geom_segment(xend = 0, yend = 0, arrow = arrow_style) +
  geom_text(
    aes(label = column),
    hjust = 1, nudge_x = -0.02, 
    color = "#904C2F"
  ) +
  xlim(-1.25, .5) + ylim(-.5, 1) +
  coord_fixed() + # fix aspect ratio to 1:1
  theme_minimal_grid(12)
```

```{r}
pca_fit |> 
  tidy(matrix = "rotation") |> 
  pivot_wider(names_from = "PC", names_prefix = "PC", values_from = "value") |> 
  ggplot
```
