---
title: "Group 25 Project"
author:
  - "André Godinho s253707"
  - "Szymon Cholewiński s253711"
  - "Magnus Strange s190867 "
  - "Lily Whipple s243865"
  - "Catarina Anastácio s253709"
format:
  revealjs: 
    theme: default # choose different themes
    logo: DTU_logo.png #choose a logo to put in here
    footer: "R for Bio Data Science 2025 - group 25 Project"
    code-block-height: 650px # maximum height of a code block, if it surpases this height becames scrollbar
    css: 
      - presentation_css.css
---

## Introduction (Szymon)

-   What are we doing
-   What is the core problem

------------------------------------------------------------------------

## Methods and Materials (Szymon)

::::: columns
R 
tidyverse in ggplot

```{r}
library("tidyverse")
library("dplyr")
library("here")
library("patchwork")
```

::: {.column width="20%"}
git colaboration
Describe pipeline
Show code
:::

::: {.column width="80%"}
it´s me
:::
:::::

## Describing the data (1) (Magnus)

-  Explain the division of variables trough the different datasets

------------------------------------------------------------------------

## Descring the data (2) (Magnus)

```{r}
#| echo: true
#| eval: true
#| output: true

iris
```

## Results (1) (Andre)

```{r}
#| output: false   # show results/output? (default true)
#| echo: true
library(ggplot2)
```

Sup

::::: columns
::: {.column width="65%"}
```{r}
#| echo: true
#| eval: false

iris |>
ggplot(mapping = 
       aes(x=Sepal.Length, 
           y=Sepal.Width)) +
geom_point()
```
:::

::: {.column width="35%"}
```{r}
#| echo: false
#| fig-height: 5
#| fig-width: 2

iris |>
ggplot(mapping = aes(x=Sepal.Length, y=Sepal.Width)) +
geom_point()
```
:::
:::::

## Results (2) (Andre) {background-color="aquamarine"}

```{r}
#| echo: true
#| eval: true
#| output: true
#| output-location: slide #slide, column, fragment, column-fragment

iris |> 
  ggplot(mapping = 
           aes(x=Sepal.Length, 
               y = Sepal.Width)) +
  geom_point()

```

## Results (3) (Catarina)

## Discussion (2) (Catarina)

## Discussion (3) (Lilly)

## Conclusion (Lilly)

quick remarks

weird data, not enough variance

other types code

ways to go forward

more data
